name: Deploy Vue and Flask Projects to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Deploy  # ✅ 这里对应你的环境名

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload Vue project to VPS
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          source: "dist/**"
          target: "/www/wwwroot/hexo/toy/"
          strip_components: 1

      - name: Upload Flask project to VPS
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          source: "flask_hello/**"
          target: "/www/wwwroot/hexo/hello/"
          strip_components: 1

      - name: Deploy Flask service
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            # 使用 conda 环境安装 Python 依赖
            cd /www/wwwroot/hexo/hello
            /data/miniconda3/envs/light/bin/pip install -r requirements.txt
            
            # 复制 systemd 服务文件
            sudo cp flask-hello.service /etc/systemd/system/
            
            # 重新加载 systemd 配置
            sudo systemctl daemon-reload
            
            # 启用并启动服务
            sudo systemctl enable flask-hello.service
            sudo systemctl restart flask-hello.service
            
            # 检查服务状态
            sudo systemctl status flask-hello.service
            
            # 更新 nginx 配置（需要手动将 nginx-hello.conf 内容添加到主配置中）
            echo "请确保 nginx 配置中包含了 /hello/ 路径的代理设置"
            echo "参考文件：nginx-hello.conf"
